on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v0'
      with:
        # NOTE You need traditional service account key to run `bq` command
        credentials_json: '${{secrets.GCP_CREDENTIALS}}'

    - uses: 'google-github-actions/setup-gcloud@v0'

    - run: bq query 'select 1;'
    - run: bq ls --projects=true --format=json

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci
    - run: npm run compile
    # NOTE
    # You'll see `Failed to connect to the bus` many time.
    # See https://github.com/microsoft/vscode-test/issues/127
    - run: xvfb-run npm test
