name: stale
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          exempt-issue-labels: rss,blocked
          exempt-pr-labels: dependencies
